# -*- coding: utf-8 -*-
"""Final Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uZu9E0TNo0D5xEqkkd1Ki7j6qJv69ojk
"""



# Step 1: Import necessary libraries
import pandas as pd

# Step 2: Load the dataset
file_path = '/boot/Fifa 23 Players Data.csv'
df = pd.read_csv(file_path)

# Step 3: Display the first 5 rows of the dataframe
df.head()

# Step 1: Check for missing values in each column
missing_values = df.isnull().sum()
print("Missing values in each column:\n", missing_values)

# Step 2: Drop irrelevant columns (e.g., image links, player names, club names, etc.)
irrelevant_columns = ['Known As', 'Full Name', 'Nationality', 'Image Link', 'Club Name', 'National Team Name',
                      'National Team Image Link', 'Club Position', 'National Team Position']
df_cleaned = df.drop(columns=irrelevant_columns)

# Step 3: Handle missing values (Drop rows with missing values)
df_cleaned = df_cleaned.dropna()

# Step 4: Convert categorical features to numeric (if needed)
from sklearn.preprocessing import LabelEncoder

# Identify categorical columns
categorical_columns = df_cleaned.select_dtypes(include=['object']).columns

# Convert each categorical column to numeric using Label Encoding
for col in categorical_columns:
    label_encoder = LabelEncoder()
    df_cleaned[col] = label_encoder.fit_transform(df_cleaned[col])

# Step 5: Display the cleaned data and check if there are still missing values
print("\nCleaned Data Overview:")
print(df_cleaned.info())
print("\nFirst 5 rows of the cleaned dataframe:")
df_cleaned.head()

# Step 1: Select relevant feature columns (statistical columns for player attributes)
relevant_columns = ['Overall', 'Potential', 'Age', 'Height(in cm)', 'Weight(in kg)',
                    'Pace Total', 'Shooting Total', 'Passing Total', 'Dribbling Total',
                    'Defending Total', 'Physicality Total', 'Crossing', 'Finishing',
                    'Heading Accuracy', 'Short Passing', 'Volleys', 'Dribbling', 'Curve',
                    'Freekick Accuracy', 'LongPassing', 'BallControl', 'Acceleration',
                    'Sprint Speed', 'Agility', 'Reactions', 'Balance', 'Shot Power',
                    'Jumping', 'Stamina', 'Strength', 'Long Shots', 'Aggression',
                    'Interceptions', 'Positioning', 'Vision', 'Penalties', 'Composure',
                    'Marking', 'Standing Tackle', 'Sliding Tackle']
df_features = df_cleaned[relevant_columns]

# Step 2: Normalize the features to have values between 0 and 1
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
df_normalized = pd.DataFrame(scaler.fit_transform(df_features), columns=df_features.columns)

# Step 3: Display the normalized data and verify
print("\nNormalized Data Overview:")
print(df_normalized.info())
print("\nFirst 5 rows of the normalized dataframe:")
df_normalized.head()

# Step 1: Import necessary libraries for clustering
from sklearn.cluster import KMeans
import matplotlib.pyplot as plt

# Step 2: Determine the optimal number of clusters using the Elbow Method
inertia_values = []
k_range = range(1, 11)  # Checking for k from 1 to 10

for k in k_range:
    kmeans = KMeans(n_clusters=k, random_state=42)
    kmeans.fit(df_normalized)
    inertia_values.append(kmeans.inertia_)

# Step 3: Plot the Elbow curve to visualize the optimal k
plt.figure(figsize=(8, 5))
plt.plot(k_range, inertia_values, marker='o', linestyle='--', color='b')
plt.xlabel('Number of Clusters (k)')
plt.ylabel('Inertia (Sum of Squared Distances)')
plt.title('Elbow Method to Determine Optimal k')
plt.show()

# Step 1: Apply K-Means clustering with the optimal number of clusters
optimal_k = 4  # Replace 4 with the k you chose based on the elbow curve
kmeans = KMeans(n_clusters=optimal_k, random_state=42)
df['Cluster'] = kmeans.fit_predict(df_normalized)  # Add cluster labels to the original dataframe

# Step 2: Display the first few rows of the dataframe to check the cluster assignment
df.head()

# Step 3: Visualize the distribution of clusters
import seaborn as sns

plt.figure(figsize=(10, 6))
sns.countplot(x='Cluster', data=df, palette='viridis')
plt.title('Number of Players in Each Cluster')
plt.xlabel('Cluster')
plt.ylabel('Number of Players')
plt.show()

# Step 1: Import necessary libraries for classification
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, accuracy_score

# Step 2: Select features and target variable for classification
X = df[['Cluster', 'Pace Total', 'Shooting Total', 'Passing Total', 'Dribbling Total',
        'Defending Total', 'Physicality Total']]  # Features for classification
y = df['Best Position']  # Target variable

# Step 3: Split the data into training and testing sets (80% train, 20% test)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Step 4: Initialize and train the KNN classifier (with k=5)
knn = KNeighborsClassifier(n_neighbors=5)  # You can change n_neighbors to fine-tune performance
knn.fit(X_train, y_train)

# Step 5: Make predictions on the test set
y_pred = knn.predict(X_test)

# Step 6: Evaluate the performance of the KNN classifier
accuracy = accuracy_score(y_test, y_pred)
print(f'KNN Classification Accuracy: {accuracy:.2f}')

# Print detailed classification report
print("\nClassification Report:")
print(classification_report(y_test, y_pred))

# Step 1: Import necessary libraries for Gradient Boosting
from sklearn.ensemble import GradientBoostingClassifier

# Step 2: Select features and target variable for classification (reusing previous features)
X = df[['Cluster', 'Pace Total', 'Shooting Total', 'Passing Total', 'Dribbling Total',
        'Defending Total', 'Physicality Total']]  # Features for classification
y = df['Best Position']  # Target variable

# Step 3: Split the data into training and testing sets (80% train, 20% test)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Step 4: Initialize and train the Gradient Boosting classifier
gbc = GradientBoostingClassifier(n_estimators=100, learning_rate=0.1, max_depth=3, random_state=42)
# You can tune these hyperparameters to improve performance

# Step 5: Train the model on the training data
gbc.fit(X_train, y_train)

# Step 6: Make predictions on the test set
y_pred = gbc.predict(X_test)

# Step 7: Evaluate the performance of the Gradient Boosting classifier
accuracy = accuracy_score(y_test, y_pred)
print(f'Gradient Boosting Classification Accuracy: {accuracy:.2f}')

# Print detailed classification report
print("\nClassification Report:")
print(classification_report(y_test, y_pred))

# Step 1: Import libraries for evaluation and visualization
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix

# Step 2: Create the confusion matrix
conf_matrix = confusion_matrix(y_test, y_pred)

# Step 3: Plot the confusion matrix
plt.figure(figsize=(10, 7))
sns.heatmap(conf_matrix, annot=True, fmt="d", cmap='Blues', xticklabels=gbc.classes_, yticklabels=gbc.classes_)
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.title('Confusion Matrix of Gradient Boosting Classifier')
plt.show()

# Step 4: Feature Importance Analysis
feature_importance = gbc.feature_importances_
feature_names = X.columns

# Create a DataFrame to visualize feature importance
importance_df = pd.DataFrame({'Feature': feature_names, 'Importance': feature_importance})
importance_df = importance_df.sort_values(by='Importance', ascending=False)

# Plot feature importance
plt.figure(figsize=(10, 6))
sns.barplot(x='Importance', y='Feature', data=importance_df, palette='viridis')
plt.title('Feature Importance in Gradient Boosting Classifier')
plt.show()

# Step 5: Save the trained Gradient Boosting model for future use
import pickle
with open('/content/gradient_boosting_model.pkl', 'wb') as file:
    pickle.dump(gbc, file)

print("Project Complete ✅")
print("The trained Gradient Boosting model has been saved as 'gradient_boosting_model.pkl'.")

# Step 6: Final Messages
print("\n🔍 Key Takeaways:")
print(f"1️⃣ Final Classification Accuracy: {accuracy:.2f}")
print("2️⃣ Check the confusion matrix to see how well the model predicted each position.")
print("3️⃣ Feature importance analysis shows the most influential skills for position prediction.")